language: generic
deploy:
  provider: s3
  access_key_id: AKIAIDNIOCEXHCTNBK4Q
  secret_access_key: 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 
  bucket: git-to-amazon-s3-max-salo-outputbucket-mxcy82um9cam
  on:
    repo: maxsalo17/MaxSalo
  acl: public_read
